### ISSUE TITLE
NV Items from Review of Production

### ISSUE THREAD

**Issue by nevillevak** [ImpactView/impact-view-philly#48] opened 2017-12-05 15:04 UTC
Hi All - Per @jcahail's email to me, I have taken a look at the production site. So great to see it coming along. It's looking great! Attached are my general comments and notes. Many of these items are probably already on your list or being worked on as we speak. Let me know if you have any questions about this or want to chat. Thanks!

[ImpactView Feedback - 120517.docx](https://github.com/ImpactView/impact-view-philly/files/1531591/ImpactView.Feedback.-.120517.docx)

**Comment by CloudNiner** [comment] 2017-12-05 22:04
Here is the full list of tasks as requested by @nevillevak:

- [x] General/Overall – Use a lighter color scheme to avoid the black backgrounds and white text. Any recommended approaches by matt is fine.

- [x] Logos at bottom, Westphal and Stanford throughout. Instead of “A Cooperative Project Of” use “A Project Of” and then the Westphal logo, and then “Supported by a Digital Impact Grant from” and then the Stanford logo. I can provide a color Westphal logo if needed.

- [x] Move map expanding icon to the right side, under or above zoom controls (easier for user to see all controls together)

- [x] Add an ‘X’ in the pop-up filter windows to show how to close the filters when done. Completed in #45.

- [ ] ~~Hover and click infowindows – originally we were going to show the org type and budget categories – these would be helpful as they’d guide the user.~~ There are a few changes requested. Will open as a separate issue.

- [x] Demographics hover text – median household income is missing the ‘d’ in ‘household’

- [x] Demographics hover text - make the text all the same size at the values displayed. Also, make the text a color that is easily readable. @designmatty 

- [x] ‘State and Region’ tab – change tab title to “Citywide Comparison” and chart headings to “Nonprofits in Selected Region” and “Nonprofits in City of Philadelphia”

- [x] Data source citations, change to:
“People and Household Data: U.S. Census Bureau, American Community Survey, 2011-2015.
Nonprofit Data: IRS Form 990/990EZ, IRS Business Master File, and Additional Data. Data Compiled by Drexel University.”

- [ ] ~~When clicking “View and Analyze” – the next screen starts at the organizational details position and doesn’t show the map above (user has to scroll up). Have page start at top.~~ Unable to reproduce. Can open as a separate issue if still a problem.

- [x] Links on the right side of the org details display: Change to “Visit Organization Website” (displayed when there’s a URL). Note that the URLs currently do not link directly to the websites (the linked URL contains impactview.org in it). 

- [x] ~~For “Submit Organization Update” I will need to set up a Gmail account to which info@impactview.org goes. Will send the details once it’s set up.~~ Duplicate of #41 

- [x] For “Print the Report” – update footer text and logo. @designmatty 

- [x] Because the custom area function is implemented (which is great!), modify the text on “Getting Started” that describes that function to state: “Use the [ICON] tool to change the radius or draw a custom area for which the data is visualized.” (added “or draw a custom area”)

- [x] In “About the Creators” hyperlink the text “Drexel University’s graduate Arts Administration” with the link http://drexel.edu/westphal/academics/graduate/AADM/. Hyperlink my name in that text with http://drexel.edu/westphal/about/directory/VakhariaNeville/

**Comment by designmatty** [comment] 2017-12-06 21:02
Is this the footer text that needs to be updated in the print report:?

`People and Household Data: U.S. Census Bureau, American Community Survey, 2010-2014.
Museum Data: Museum Universe Data File, Compiled by IMLS and Drexel University.`

**Comment by jcahail** [comment] 2017-12-06 21:07
@designmatty yes- should be replaced with “People and Household Data: U.S. Census Bureau, American Community Survey, 2011-2015. Nonprofit Data: IRS Form 990/990EZ, IRS Business Master File, and Additional Data. Data Compiled by Drexel University.”

**Comment by nevillevak** [comment] 2017-12-06 21:26
Correct! Thanks!

Best,
Neville
_________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
URBN Center, Suite 210
nvakharia@drexel.edu<mailto:nvakharia@drexel.edu>
215.571.4439

**Closed as completed** 2017-12-08 20:10 UTC
